### ISSUE TITLE
when installed Proxyman my command+f failed to work everywhere!

### ISSUE THREAD

**Issue by wunshine** [ProxymanApp/Proxyman#102] opened 2019-04-03 07:54 UTC
### Screenshots (optional)

when installed Proxyman, i just found that my command+f failed in Xcode and chrome,and then my command+f was not work everywhere.
After uninstalled Proxyman ,everything workes well again.

**Comment by NghiaTranUIT** [comment] 2019-04-03 08:52
Hey @wunshine 

This issue is known-issues and it was fixed in Proxyman 1.3.2 (https://github.com/ProxymanApp/Proxyman/issues/45)

If you're using old version. It's time to upgrade it to Proxyman 1.3.4 at https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4

**Comment by NghiaTranUIT** [comment] 2019-04-03 08:54
I can't reproduce it in OS 10.14. If you don't mind, which macOS are you using 🤔 

I would like to take a look on it, when it's annoying bug 🥺

**Comment by wunshine** [comment] 2019-04-03 09:19
─>🤓  brew cask install proxyman
==> Satisfying dependencies
==> Downloading https://github.com/ProxymanApp/Proxyman/releases/download/1.3/Pr
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'proxyman'.
==> Installing Cask proxyman
==> Moving App 'Proxyman.app' to '/Applications/Proxyman.app'.
🍺  proxyman was successfully installed!

Mac os version 10.14.4.

**Comment by NghiaTranUIT** [comment] 2019-04-03 09:37
Hey thank for the log ⚡️,

For some reasons, your brew cask repository is out of date. From the log you sent, you're installing Proxyman **1.3**, not **1.3.4** (https://github.com/Homebrew/homebrew-cask/pull/61222)
 
Can you try to upgrade your cask?

Or just open the Proxyman -> **Check for Update...**
<img width="267" alt="Screen Shot 2019-04-03 at 16 35 56" src="https://user-images.githubusercontent.com/5878421/55468907-97fdfc80-562e-11e9-974a-20d0b5f49d4f.png">

Thank for bounding 😁

**Comment by NghiaTranUIT** [comment] 2019-04-03 09:39
@wunshine The output of brew cask should have `1.3.4`

For instance,
```
❯ brew cask install proxyman                                                                                                                         ✭
==> Satisfying dependencies
==> Downloading https://github.com/ProxymanApp/Proxyman/releases/download/1.3.4/Proxyman_1.3.4.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/142885098/46604100-5479-11e9-9ce5-7c6963e6c771?X-Amz-Algorithm=AWS
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'proxyman'.
==> Installing Cask proxyman
==> Moving App 'Proxyman.app' to '/Applications/Proxyman.app'.
🍺  proxyman was successfully installed!
```

**Comment by NghiaTranUIT** [comment] 2019-04-03 12:51
Hey @wunshine 

Here is the hot-fix for your issue 🔥 https://www.dropbox.com/s/a6jbgzstgefp5uv/Proxyman_1.3.4.dmg?dl=0

Thank you for using Proxyman 👍

**Comment by wunshine** [comment] 2019-04-03 13:59
ok, thank you  
I'll try to update my cask and install again

**Comment by NghiaTranUIT** [comment] 2019-04-03 14:09
Awesome man 😍

**Closed** 2019-04-03 15:08 UTC
Labels: bug

**Comment by NghiaTranUIT** [comment] 2019-04-07 16:22
I actually refactor the logic of HotKey in [Proxyman 1.3.4.1](https://github.com/ProxymanApp/Proxyman/releases/tag/1.3.4.1). 

Technically, I removed completely the Global Hotkey, and replacing with Hot key with First Responder, so the other will never be conflicted. This approach seems to be better than the last one.

Thank you guys 🥺
