### ISSUE TITLE
 local mapping editor is unable 

### ISSUE THREAD

**Issue by jinean** [ProxymanApp/Proxyman#1596] opened 2023-04-11 03:19 UTC
## Description
I upgraded to Version 4.6.0 (46000) today and found that my local mapping editor is unable to view mapped text anymore.

![image](https://user-images.githubusercontent.com/2232297/231047562-36c195d2-dbec-457c-be99-8d8fd3d00f8d.png)

**Comment by NghiaTranUIT** [comment] 2023-04-11 03:35
Hi,

Can you try to use the old version 4.5.0 and check if it fixes?

**Comment by NghiaTranUIT** [comment] 2023-04-11 07:49
It's odd. We could not reproduce your bug on the latest version 4.6.0.

Just wondering: What macOS version you're using? @jinean

**Comment by jinean** [comment] 2023-04-11 07:59
13.3 (22E252)

**Comment by NghiaTranUIT** [comment] 2023-04-11 08:47
Does Quit and Reopen the app will fix the bug @jinean ?

I'm using macOS 13.3.1 and v4.6.0 without any issues.

![CleanShot 2023-04-11 at 15 45 22@2x](https://user-images.githubusercontent.com/5878421/231106512-553d868d-1bec-4702-86ce-5ddbaec1ddd8.jpg)

---------

The main different between v4.4.0 and v4.5.0 or v4.6.0 is: We introduce a new Editor. You can see the screenshot at https://github.com/ProxymanApp/Proxyman/releases/tag/4.5.0

**Comment by jinean** [comment] 2023-04-12 02:24
It's very strange.
I upgraded my Mac mini to 13.3.1 this morning and it still doesn't show up.
I went home last night and used my MacBookPro at home. I tried 13.0 and 13.3.1 systems and they all worked fine.

**Comment by jinean** [comment] 2023-04-12 02:24
It's very strange.
I upgraded my Mac mini to 13.3.1 this morning and it still doesn't show up.
I went home last night and used my MacBookPro at home. I tried 13.0 and 13.3.1 systems and they all worked fine.

**Comment by NghiaTranUIT** [comment] 2023-04-12 02:34
If the Map Local Editor doesn't display on your Mac Mini 13.3.1. Can you verify that you can see the Body of any Request and Response?

It means the Monaco Editor (which uses for the Map Local Editor) is working.

![Screenshot 2023-04-12 at 09 33 40](https://user-images.githubusercontent.com/5878421/231333043-8af34775-2783-44cd-b3d5-6c12ac6f9305.jpg)

**Comment by jinean** [comment] 2023-04-12 02:55
I just saw that the body is empty

And I found that the Body in Compose can no longer be edited

It feels like the TextView view has disappeared
![image](https://user-images.githubusercontent.com/2232297/231336197-f2049226-f226-42a8-be1d-65a48932af34.png)
![image](https://user-images.githubusercontent.com/2232297/231336267-c0f8b6cd-8e05-45b1-89e4-6519f7ee162d.png)

**Comment by NghiaTranUIT** [comment] 2023-04-13 02:56
Yes, look like the Body doesn't load properly in your machine. Just wondering: Quit the app, then opening it again will fix your bug?

I'm not sure what cause the bug since I could not reproduce it on our end 😢

**Comment by 1414044032** [comment] 2023-04-13 11:02
I have a friend who has also encountered this problem. He is upgrading the system to see if it can be done

**Comment by 1414044032** [comment] 2023-04-13 11:04
Before upgrade: IOS: 13.2.1

**Comment by jinean** [comment] 2023-04-14 01:23
> Yes, look like the Body doesn't load properly in your machine. Just wondering: Quit the app, then opening it again will fix your bug?
> 
> I'm not sure what cause the bug since I could not reproduce it on our end 😢

I have tried various restarts, but none of them work.

**Comment by NghiaTranUIT** [comment] 2023-04-14 02:00
@jinean I'm investigating it and send you a hotfix Beta asap 👍

**Comment by NghiaTranUIT** [comment] 2023-04-14 03:31
@1414044032 @jinean, if you don't mind, please try using this Beta build: https://download.proxyman.io/beta/Proxyman_4.6.0_Fix_Monaco_Editor_Body_could_not_load.dmg

Basically, I fixed the bug where the Local Monaco Server doesn't work. If it happens, it tried to load the static page instead. It makes sure the body is loaded 100% 👍 

Let me know the result too 👍

**Comment by jinean** [comment] 2023-04-14 07:04
> @1414044032 @jinean, if you don't mind, please try using this Beta build: https://download.proxyman.io/beta/Proxyman_4.6.0_Fix_Monaco_Editor_Body_could_not_load.dmg
> 
> Basically, I fixed the bug where the Local Monaco Server doesn't work. If it happens, it tried to load the static page instead. It makes sure the body is loaded 100% 👍
> 
> Let me know the result too 👍

It's still not showing even after trying, it has no effect.

**Comment by NghiaTranUIT** [comment] 2023-04-14 07:07
@jinean  please help me

1. Download the above beta build -> Drag to /Applications folder
2. Close all Proxyman -> Open Terminal app -> Run: `open /Applications/Proxyman.app/Contents/MacOS/Proxyman`
3. It will display the Proxyman app
4. If the body doesn't show again -> Please copy to me the error log on the Terminal app 👍

**Comment by jinean** [comment] 2023-04-14 07:23
> @jinean please help me
> 
> 1. Download the above beta build -> Drag to /Applications folder
> 2. Close all Proxyman -> Open Terminal app -> Run: `open /Applications/Proxyman.app/Contents/MacOS/Proxyman`
> 3. It will display the Proxyman app
> 4. If the body doesn't show again -> Please copy to me the error log on the Terminal app 👍

❌ [MonacoEditor] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorDomainKey=12, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4C899E7D-5439-4D52-8018-7942296A3AE8>.<10>, NSErrorFailingURLStringKey=http://localhost:10382/index.html, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found., _WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x6000009f9180>, networkTaskDescription=LocalDataTask <4C899E7D-5439-4D52-8018-7942296A3AE8>.<10>, NSErrorFailingURLKey=http://localhost:10382/index.html, NSUnderlyingError=0x6000003649c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, networkTaskMetricsPrivacyStance=NotEligible}

After checking the log, I figured out the problem. It seems that my local hosts file was corrupted or overridden. I added '[127.0.0.1](http://127.0.0.1/) localhost' and now it's displaying properly.

**Comment by NghiaTranUIT** [comment] 2023-04-14 07:25
ah, I see. It's better to load `http://127.0.0.1:<port>` instead of using the `localhost`. Let me fix it 👍

**Comment by NghiaTranUIT** [comment] 2023-04-14 08:01
It's fixed @jinean @1414044032 👍

**Comment by NghiaTranUIT** [comment] 2023-04-14 10:54
Fixed with this Beta build: https://download.proxyman.io/beta/Proxyman_4.6.0_Fix_Monaco_Editor_v2.dmg

**Comment by NghiaTranUIT** [comment] 2023-04-14 12:28
Good news: I've bumped the hot-fix v4.6.1. It's fixed the issue 👍 

Thanks to everyone who helps me to investigate the bug 🙇

**Closed** 2023-04-14 14:12 UTC
Labels: question, ✅ Done
