### ISSUE TITLE
[Nice to have] Allow to hide useless requests (without blocking them)

### ISSUE THREAD

**Issue by speekha** [ProxymanApp/Proxyman#913] opened 2021-06-22 14:21 UTC
### macOS Version? mac 10.15.6

When I connect my Android simulator to Proxyman, lots of requests go through that have zero interest to me (either from third party libs or apps). All those request tend to clog logs a lot with pointless information. The block list option can allow to remove some of those, except that blocking the request can alter the behavior of my app. So instead of blocking completely the requests, I'd like to have an option to just hide those requests from the captured logs so I only keep the requests that make sense to me.

**Comment by NghiaTranUIT** [comment] 2021-06-22 14:24
If you use iOS Simulator, Proxyman is already hiding all unnecessary traffic from the iOS Simulator to Apple Server. However, it hasn't implemented for the Android Emulator yet.

Can you share with us the list of unnecessary APIs from your Emulator?

-------------------

To workaround, you can either:
1. Pin your working domain (Right Click on the domain -> Pin to Favorites)
2. Filter your working domain with a filter or multiple filters

**Comment by speekha** [comment] 2021-06-22 22:01
Well there are actually a lot of different URLs transiting through proxyman on my project, on a lot of different domains.
So on one hand, the requests I'm interested in are on several domains, so filter won't really work (but I guess I could pin all those domains). On the other hand, it's not just standard simulator stuff I want to filter out : we include a lot of third party libs that send requests on a lot of other domains (analytics and other third party services). So basically there are lots of URL or domains I'd like to exclude, but also lots of domains to let through (and I'd rather exclude explicitly the ones I'm not interested in so I can notice anything unusual, rather than miss it because it's not in the pinned ones).

**Comment by NghiaTranUIT** [comment] 2021-06-23 01:34
So, if these unnecessary domains are not from a standard Android Emulator, it's impossible for us to automatically hide it.

On the other hand, it works for iOS Simulator, since they're all from *.apple.com.

I would like to recommend that you should pin your working domain, group it into a folder. Then selecting the folder -> It will list all traffic from these domains. Therefore, you can exclude other unnecessary requests.

----------------------------
However, it's a nice idea to implement a feature "something like Hidden/Exclude List", to hide these domains without explicitly blocking them.

**Comment by crankygeek** [comment] 2021-07-02 16:40
I think this is a dupe of my request #594.

**Comment by speekha** [comment] 2021-07-02 17:17
@crankygeek Agreed. Sorry I didn't see yours.

**Comment by crankygeek** [comment] 2021-07-02 17:19
@speekha No worries! I just wanted to link the tickets. I probably should have worded that better.

**Comment by NicolasCombe5555** [comment] 2021-12-16 02:56
+1 🚀

**Comment by NghiaTranUIT** [comment] 2021-12-17 01:45
@NicolasCombe5555 if you don't mind, can you share with me what kind of traffic you want to hide from your app? 🤔 Is it ads, analytic traffic?

**Comment by NicolasCombe5555** [comment] 2021-12-21 16:44
@NghiaTranUIT sorry for the late response. Mmm for example in my app I  get periodically updates from open connections, if I add to the block list tho, the app does not behave like it normally would. So for example in that case it would be useful to just ignore a certain url pattern but not block it, so I do not have spam when I try to debug other things; I believe it would be useful to have this feature like @speekha said as well.

**Comment by chilikasha** [comment] 2022-01-06 09:28
Would also like to have this feature. I have numerous "subscribe event" requests which I would like to filter out.

**Comment by NghiaTranUIT** [comment] 2022-01-06 14:12
Thanks @NicolasCombe5555 @chilikasha and others. I understand that this feature should be implemented since it's recently gained more attention 😄 

Just a simple mock-up: Instead of implementing a new tool (New feature), I suppose that I can improve the Block Tool.

By adding the option to:
- Block and Hide: Your request are blocked and hidden from the app.
- Hide but not Block: Your requests still go through the server and are hidden from the app.

<img width="880" alt="Screen_Shot_2022-01-06_at_21_08_48" src="https://user-images.githubusercontent.com/5878421/148395547-fbb8d405-1827-441d-b3b6-bd032facc205.png">

I will implement and sent you guys a Beta build soon 👍

**Comment by NghiaTranUIT** [comment] 2022-01-10 02:38
Hey @NicolasCombe5555 @chilikasha @speekha @crankygeek let try this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.35.4_Hide_Request_From_Block_Tool.dmg

You can simply hide the requests, without blocking them 👍 

You can simply create a rule by Righ-Click on the Request -> Tools -> Block List -> Select Block Action as "Hide, but not Block" 😄 

<img width="1647" alt="Screen_Shot_2022-01-10_at_09_34_25" src="https://user-images.githubusercontent.com/5878421/148712355-4a5ceef7-3bd8-4782-ad65-22bc4f63ca43.png">

**Comment by chilikasha** [comment] 2022-01-10 10:31
@NghiaTranUIT looks like it works as expected for me :) thank you!

**Comment by crankygeek** [comment] 2022-01-10 22:01
@NghiaTranUIT Looks to be working well.

**Comment by NicolasCombe5555** [comment] 2022-01-10 22:47
@NghiaTranUIT working good! thanks 🚀🎉🎉

**Comment by NghiaTranUIT** [comment] 2022-01-11 02:05
Awesome, I will release this feature on the next version 🎉

**Comment by user1man** [comment] 2024-04-24 22:43
Hello everyone,

Thank you for your contributions to this discussion. It would be beneficial if we could mark this issue as resolved. This would assist anyone who comes across this thread in the future to understand that the feature request has been implemented.

Thank you for your understanding and cooperation.

**Comment by NghiaTranUIT** [comment] 2024-04-25 00:48
yes, it's done with the `done` tag 👍

**Closed by NghiaTranUIT** 2024-04-25 00:48 UTC
Labels: ✅ Done, Feature request
