### ISSUE TITLE
Not working WebSocket

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ProxymanApp/Proxyman#586] opened 2020-08-18 16:08 UTC
### Proxyman version? (Ex. Proxyman 1.4.3)
2.4.3
### macOS Version? (Ex. mac 10.14)
10.15.6
### Steps to reproduce 
Just run Proxyman and start websocket session.
In iOS app that i'm developing are enabled some wss communications. I'm seeing in logs that the communications are going on.
But there's none any websocket session in Proxyman neither in all logs or in such filter. All other connections both http and https are showing well, so the app is configured well. But wss not even trying.

This behavior reproduces on both iOS device with Proxyman MiTM and in fully configured with for Proxyman iOS Simulator.
### Expected behavior
To get logs (at least failed) in proxyman logs.

**Comment by NghiaTranUIT** [comment] 2020-08-19 03:45
Please make sure you enable SSL-Proxying for the Domain that WebSocket occurs. Then you can see WSS traffic and be able to filter out by WSS filter 👍 

Technically, if we don't enable SSL-Proxying on this domain, WSS connect would **act** as an HTTPS CONNECT request. Thus, Proxyman doesn't know if it's a normal HTTPS or WSS under the hood until we enable SSL. Therefore, you couldn't filter the WSS in the first place.

After we enable SSL-Proxying, Proxyman is able to read the header and understand that it's a WSS and handle the WSS traffic.

![Screen_Shot_2020-08-19_at_10_24_20](https://user-images.githubusercontent.com/5878421/90589685-d89cec80-e208-11ea-929b-38256cf261f8.png)

![Screen_Shot_2020-08-19_at_10_25_25](https://user-images.githubusercontent.com/5878421/90589694-e05c9100-e208-11ea-93d8-6aeca4141cd6.png)

**Comment by NghiaTranUIT** [comment] 2020-08-19 04:30
If it still doesn't work, please share with me the AppStore link that I can reproduce in my end. I tried Websocket on Slack iOS app, Github web, and JS WS, and it works well 👍

**Comment by yaroslavyaroslav** [comment] 2020-08-19 09:49
This helps, but i've got another one error. It seems that i've got this error on every websocket conenction.
![Снимок экрана 2020-08-19 в 12 45 08](https://user-images.githubusercontent.com/16612247/90619846-67663500-e21a-11ea-9179-27d5f05796c6.png)

**Comment by yaroslavyaroslav** [comment] 2020-08-19 09:55
Oh, another correction. It works (thank you), but mostly it fails with some error.
![Снимок экрана 2020-08-19 в 12 51 31](https://user-images.githubusercontent.com/16612247/90620444-20c50a80-e21b-11ea-8ff0-b6420acbf96f.png)
![Снимок экрана 2020-08-19 в 12 51 07](https://user-images.githubusercontent.com/16612247/90620439-1efb4700-e21b-11ea-8e59-cc0ad2849f12.png)

**Comment by NghiaTranUIT** [comment] 2020-08-19 10:00
Those errors are fixed on #589 👍

**Comment by NghiaTranUIT** [comment] 2020-08-19 10:01
I gonna release tonight 😻

**Comment by yaroslavyaroslav** [comment] 2020-08-20 15:33
I'm still having errors on 2.4.2. 
![Снимок экрана 2020-08-20 в 18 32 15](https://user-images.githubusercontent.com/16612247/90792807-9d3b1480-e313-11ea-99d2-9c2fc3c69aae.png)

**Comment by NghiaTranUIT** [comment] 2020-08-20 15:35
Thanks. I'm aware too. There are few unnecessary WebSocket flows that #589 doesn't completely fix. I'm fixing now 👍

**Comment by adampetrovic** [comment] 2020-11-01 20:50
None of the above instructions make the Websocket connection show in Proxyman. I have the `*` wildcard added as SSL. The websocket connect works for the Slack app but not another app i'm working with. Any ideas if apps can set up websockets in a way that makes them not compatible with Proxyman?

**Comment by NghiaTranUIT** [comment] 2020-11-02 02:06
Hey @adampetrovic, it's a known issue that we're facing regarding the WebSocket.

The reason why you don't see WebSocket domains from your app is that they are using SOCKS5 Proxy, not HTTP Proxy. Unfortunately, Proxyman hasn't supported SOCKS5 yet. You can verify by using other tools like Charles Proxy (not enable SOCK5), and try to capture Websocket traffic. It doesn't show too.

To fix it, Proxyman has to implement the "SOCKS5 Proxy" and "Enable HTTP Proxy over SOCKS Proxy" feature in order to capture the WebSocket Traffic.

For instance, URLSessionWebSocketTask uses SOCKS5 Proxy. Therefore, WS traffic doesn't go through HTTP Proxy (Proxyman at 9090), we could not see it 😿

**Comment by NghiaTranUIT** [comment] 2021-04-16 09:40
Hey @yaroslavyaroslav @adampetrovic @JohnCoates, @adampetrovic,@nuno-vieira, and @tema-orange

If you would like to capture WS/WSS from URLSessionWebsocketTask, let try Atlantis Framework 👍 

Basically, it does "Method Swizzling" for all WS/WSS methods, capture all WS traffics, then sending it to Proxyman for preview (See the Screenshot)

![Screen_Shot_2021-04-16_at_16_28_20](https://user-images.githubusercontent.com/5878421/115005103-b9f31080-9ed1-11eb-9536-75fee6549eb8.png)

### Install
1. Download this Proxyman Beta: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.23.0_Capture_WebSocket_Atlantis.dmg
2. Get Atlantis on the `main` branch (It's not released yet)
```
pod 'atlantis-proxyman', :git => 'https://github.com/ProxymanApp/atlantis.git', :branch => 'main'
```


### Ref
- https://github.com/ProxymanApp/atlantis/pull/66

**Comment by adampetrovic** [comment] 2021-04-16 09:49
I don't have any control over the app i'm wanting to sniff. Looking at the instructions it seems Atlantis is a dependency you install inside your iOS project. How do I capture WS traffic of existing apps?

**Comment by NghiaTranUIT** [comment] 2021-04-16 09:50
You're right. You have to install Atlantis to your app in order to capture the WS traffic. @adampetrovic

At the moment, there is no solution to capture WS/WSS from iOS 14. All Proxy apps I tried that didn't work too

**Comment by yeradis** [comment] 2021-04-17 07:23
@NghiaTranUIT I'm facing this issue too, 

something that would be nice is to have the option to exclude HTTPS Response inspection on specific protocols/methods or connections for the same domain you want to check response, mainly exclude for example CONNECT method

**Comment by vjpr** [comment] 2021-04-17 07:39
Charles supports SOCKS5. https://stackoverflow.com/questions/6248674/debugging-iphone-traffic-using-charles-proxy-socks-feature

**Comment by NghiaTranUIT** [comment] 2021-04-17 07:41
Yes @vjpr, Charles supports SOCKS5 but I'm unable to capture WS/WSS traffic from the iOS app (iOS 14). I tried a few solutions, but none of them work. Not sure how make it works 🤔

**Comment by yaroslavyaroslav** [comment] 2021-04-17 23:37
@NghiaTranUIT Is there spm support?

**Comment by NghiaTranUIT** [comment] 2021-04-18 02:33
@yaroslavyaroslav It supports SPM too, please make sure you get the master branch because this feature is not officially released yet 👍

**Comment by JohnCoates** [comment] 2021-04-19 01:27
Are there any plans to implement SOCKS5? I'm targeting apps that don't use `URLSessionWebsocketTask`

**Comment by NghiaTranUIT** [comment] 2021-04-19 02:01
Yes, @JohnCoates it's in a plan, but from what I tried, I enable Socks5 proxy on Charles Proxy, but I'm still unable to get the WS/WSS traffic from the app. 
Therefore, If I support it, I still don't know whether or not it works 🤔

**Comment by tkrajacic** [comment] 2021-12-21 19:27
Is there any progress on this being made? I love Proxyman but as I am currently working with many websockets I dearly miss being able to use it 😭

**Comment by nuno-vieira** [comment] 2021-12-21 22:05
@tkrajacic I would strongly recommend you to install this as a dev dependency of your project: https://github.com/ProxymanApp/atlantis. You just need to make sure it is a dev dependency, and don't ship this to the product. 

With Atlantis, you can easily observe web socket traffic and you also don't need to set up certificates etc, is much easier to use Proxyman with Atlantis 🙂

**Comment by NghiaTranUIT** [comment] 2021-12-22 01:59
@tkrajacic Proxyman can capture WS/WSS from your Macbook (by GoogleChrome, Safari, Firefox, ...) out of the box. However, if you're talking about WS/WSS from iOS devices, it's a different story.

As @nuno-vieira commented, I highly recommend this solution too because it works seamlessly with WS/WSS from your iOS apps 👍 

-----------------
Basically, WS/WSS on iOS apps doesn't respect the System HTTP Proxy, so Proxyman could not capture it

**Comment by tkrajacic** [comment] 2021-12-22 02:38
@nuno-vieira and @NghiaTranUIT I can somewhat understand (and don't take offence in) that you immediately assume that I didn't read the dozens of comments regarding this issue and regurgitate what's been suggested before, but that doesn't answer my question really… 

I am running tests of a macOS SPM package that connect to WebSockets and that doesn't even work with Atlantis afaict.

**Comment by NghiaTranUIT** [comment] 2021-12-22 02:45
Sorry @tkrajacic, I don't mean that. Just wondering: What Websocket library are you using? (Starscream, URLSessionWebsocketTask, ...)

**Comment by tkrajacic** [comment] 2021-12-22 02:49
`URLSessionWebsocketTask`, and I know all about why it doesn't work. Hence my question. 🙃

**Comment by NghiaTranUIT** [comment] 2021-12-22 09:32
@tkrajacic I've updated Atlantis to make it possible to integrate to Swift Playground 👍 

<img width="1329" alt="Screen_Shot_2021-12-22_at_16_30_15" src="https://user-images.githubusercontent.com/5878421/147070257-c2e4bbb3-e263-439a-bf7d-85f981d59678.png">

- Here is how to set up: https://github.com/ProxymanApp/atlantis#3-use-atlantis-on-swift-playground
- Sample Code: https://github.com/ProxymanApp/Atlantis-Swift-Playground-Sample-App/blob/master/MyPlayground.playground/Contents.swift

**Comment by tkrajacic** [comment] 2021-12-22 09:40
@NghiaTranUIT While this is nice, please stop suggesting things that I don't ask for, nor need.
I don't have a Playground, and don't intend to add one to the project, and I also don't intend to add a dependency solely for the purpose of letting an external tool capture my web traffic. That's exactly why one uses a mitm proxy like Proxyman.

Now I fully understand that implementing actually capturing WebSocket traffic now that it somehow goes through the SOCKS5 proxy might be hard, annoying, unknown even, but all of that are good reasons to say: "No I am not working on it", or "yes, I am still looking into it". Even saying "I want to wait and see if anyone else like Charles can pull it off first so I don't waste my time" is a totally valid reason, which I wholeheartedly support.
Proposing solutions to questions that weren't asked is not the right thing to do though.

**Comment by tkrajacic** [comment] 2021-12-22 09:42
And just to give this conversation the appropriate tone:

Proxyman is amazing. It's beautiful, super well crafted, incredibly full-featured! You are doing a fantastic job!

**Comment by NghiaTranUIT** [comment] 2022-03-25 01:40
Yes @garvan-slack , it's a technical problem with Proxyman and other web debugging proxy apps (Charles Proxy, Fiddler). Basically, it's impossible to capture traffic from `URLSessionWebSocketTask`.

If you know feasible solutions, please share them with me. I appreciate and try to bring it to Proxyman.

To workaround, I highly suggest using the [Atlantis framework](https://github.com/ProxymanApp/atlantis) + Proxyman, since it's built for it 👍

**Closed** 2022-12-15 08:22 UTC

**Comment by NghiaTranUIT** [comment] 2023-08-12 01:33
@StanislavMayorov yes, it's true, if you're using URLSessionWebSocketTask. I suggest using [Atlantis](https://github.com/ProxymanApp/atlantis) + Proxyman to inspect websocket 👍

**Comment by StanislavMayorov** [comment] 2023-08-12 09:13
@NghiaTranUIT I have already set up [Atlantis](https://github.com/ProxymanApp/atlantis), but it doesn't show react native websocket. RN [implementation](https://github.com/facebook/react-native/blob/7bc2b730a8b5994ade1dfa66769e5ec60cfc05fb/packages/react-native/React/CoreModules/RCTWebSocketModule.mm) use [SocketRocket](https://github.com/facebookincubator/SocketRocket/blob/main/SocketRocket/SRWebSocket.h). Is it possible to integrate atlantis to SocketRocket?

**Comment by FranklinSamboni** [comment] 2024-05-22 15:25
I know this ticket has been closed. Just want to let know to the developers that are still facing this issue and don't want to use Atlantis, I know that many developers don't really want to add another dependency to their project just for debugging purposes.

There is this new `ProxyConfiguration` https://developer.apple.com/documentation/network/proxyconfiguration, we can use to set a socksv5Proxy for our NWConnection throughout NWParameters, URLSession, URLRequest or WKWebView, it is only available for iOS 17 and above. 

We will just need to enable SOCKSV5 in Proxyman and set the proxy server details in our connection. 

Proxyman Setup:
Tools > Proxy Settings > SOCKS Proxy settings -> Enable it

App Setup: 
Configure a Socksv5Proxy in your App, make sure this is only available for debug builds by implementing a switch or something, you might not want your release build with configuration. 

This is for NWConnection, but you should be able to do it for URLSession, URLRequest or WKWebView See: https://developer.apple.com/videos/play/wwdc2023/10002/

```
        let parameters = webSocketURL.scheme == "wss" ? NWParameters.tls : NWParameters.tcp

        let options = NWProtocolWebSocket.Options()
        options.autoReplyPing = true

        parameters.defaultProtocolStack.applicationProtocols.insert(options, at: 0)

        if #available(iOS 17.0, *) {
            let socksv5Proxy = NWEndpoint.hostPort(host: "192.168.1.4", port: 8889)
            let config = ProxyConfiguration.init(socksv5Proxy: socksv5Proxy)
            let context = NWParameters.PrivacyContext(description: "my socksv5Proxy")
            context.proxyConfigurations = [config]

            parameters.setPrivacyContext(context)
        }

        let connection = NWConnection(to: .url(webSocketURL), using: parameters)
        connection.start(queue: .main)
```

Now all your WebSocket Connection traffic is going throughout Proxyman for debugging purposes.

**Comment by NghiaTranUIT** [comment] 2024-05-23 03:56
Awesome @FranklinSamboni I will add this Websocket Docs: https://docs.proxyman.io/advanced-features/websocket 👍 

Really appreciate your help 🙇

**Comment by Mup0c** [comment] 2024-05-25 20:40
Guys, @NghiaTranUIT, I accidentally came across this thread and would like to share a method for proxying websockets on iOS (15.8.2 tested) without changing any configurations and without even having the source code of the app. Using the Potatso app on iOS (I believe there are other similar apps that allow you to connect to proxies, while iOS will show it as a VPN), connect to your proxy, HTTP or Socks5, it doesn't seem to matter. And that's it. (I use Charles, I understand that Proxyman is discussed, but still, I hope that helps).
