### ISSUE TITLE
HTTP operations not completing

### ISSUE THREAD

**Issue by tiwood** [ProxymanApp/Proxyman#471] opened 2020-04-06 12:02 UTC
### Proxyman version? (Ex. Proxyman 1.4.3)

Version 1.21.0 (12100)

### macOS Version? (Ex. mac 10.14)

macOS 10.15.4

### Steps to reproduce 

While using `Proxyman` my `Terraform` command fails, as `Terraform` is unable to save the state to an `Azure Storage Account` - the same works with `Carles Proxy`.

This happens while using `Proxyman`:

![image](https://user-images.githubusercontent.com/6249819/78546326-7d400400-77fd-11ea-8c72-97cd6d048cc5.png)

The `CONNECT` never completes.

Update:

I've just tried the Tool `Azure Storage Explorer` to browse the `Storage Account` while using `Proxyman` and it seems various operations never complete there too:

![Screenshot 2020-04-06 at 12 13 55 PM](https://user-images.githubusercontent.com/6249819/78548002-44555e80-7800-11ea-8ea1-8f66bdd65c36.png)

The whole tool is not working with Proxyman.

**Comment by NghiaTranUIT** [comment] 2020-04-06 12:04
Thank for the report 👍 I will investigate it on this week 🌮

**Comment by NghiaTranUIT** [comment] 2020-04-06 12:13
@tiwood Does it only happen on this build 1.21.0 and working well in the old build?

**Comment by tiwood** [comment] 2020-04-06 12:26
The problem also happened in older releases.

**Comment by NghiaTranUIT** [comment] 2020-04-12 06:52
Hey @tiwood, please help me to create a Storage Account at nghia@proxyman.io

On preliminary investigation, the normal traffic from Azure Storage Explorer is working well, but I reproduce the bug on the Storage API.

Thank you in advance 🙇

**Comment by tiwood** [comment] 2020-04-12 08:56
Hey @NghiaTranUIT, I've sent you the details to nghia@proxyman.io

**Comment by christos** [comment] 2020-04-27 17:50
This looks similar to the behaviour I am seeing at #488 but completely different endpoint/app.

**Comment by NghiaTranUIT** [comment] 2020-04-28 01:52
I will investigate this bug later after #448 is done 🙌

**Comment by NghiaTranUIT** [comment] 2020-06-18 02:55
Hi @tiwood and @christos, since the Proxyman v2, which is fully rewritten with Swift NIO, your issues should be fixed (https://github.com/ProxymanApp/Proxyman/releases/tag/2.0.0)

Please update and check it out 🙌

**Closed** 2020-06-29 17:28 UTC
Labels: bug
