### ISSUE TITLE
Allow disabling SSL certificate verification

### ISSUE THREAD

**Issue by seidnerj** [ProxymanApp/Proxyman#1758] opened 2023-09-02 09:05 UTC
## Description

When Proxyman executes requests on behalf of a client, or via the "Proxyman Networking" process (e.g. when using the web view preview tab), it validates the SSL certificate of the target server. It would be helpful if this could be disabled via a menu item.

## Why this feature/change is important?

In many cases, especially in development scenarios, this is undesired for various reasons since SSL certificates are not ready/still incompatible, or when using IP addresses directly (for which the SSL certificates are not valid).

## Example screen shot from the app
<img width="1726" alt="Screenshot 2023-09-01 at 18 24 08" src="https://github.com/ProxymanApp/Proxyman/assets/4147381/3bf5641d-6770-44b8-a246-490b2295404a">

**Comment by NghiaTranUIT** [comment] 2023-09-03 08:47
@seidnerj can you try this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_4.10.0_disable_ssl_verification_on_webview.dmg

I couldn't reproduce your issue, so I tried to disable the SSL Verification in the WKWebview according to [Apple Guideline](https://developer.apple.com/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication)

**Comment by seidnerj** [comment] 2023-09-03 12:14
Works great, thanks a lot! The way you can reproduce this with the current version is to open Proxyman, "Override macOS settings" then run this curl request noted below (172.217.22.100 is one of the servers for www.google.com), and try to view the response using the Webview tab.

curl 'https://172.217.22.100/' \
-H 'Host: www.google.com' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15' \
-H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
-H 'Accept-Encoding: identity' \
--proxy http://localhost:9090 -k

This might also apply to requests done by Proxyman generally on behalf of the origin client, no? also - might be a good ID to enable/disable SSL verification in general as this could be a security hazard. 

Thanks a lot for the prompt response! 🙏

**Comment by NghiaTranUIT** [comment] 2023-09-03 12:35
Awesome, Glad to know it works fine 👍

**Comment by seidnerj** [comment] 2023-09-04 13:32
Will this be included in the next version?

**Comment by NghiaTranUIT** [comment] 2023-09-04 13:32
Yes, it will be included in the next release 4.11.0 👍

**Closed** 2023-09-08 20:54 UTC
Labels: enhancement, ✅ Done
